export type PathId = 'P1' | 'P2' | 'P3' | 'P4' | 'P5' | 'P6';
export type EnemyKind = 'poopGuardian' | 'offLeashGuardian' | 'dogTrader' | 'illegalBreeder';
export type EnemyVariant = 'male' | 'female';
export type EnemyState = 'moving' | 'windup' | 'holding' | 'dead';
export type PurchasableSkillId = 'tailSwipe' | 'aquaBeam' | 'safetyReport';
export type PlayerActionId = 'bark' | PurchasableSkillId;
export type SkillCost = 15 | 20 | 25 | 30 | 40 | 45;
export type DamageSource = 'bark' | 'deokbae' | PurchasableSkillId;
export type ImpactStrength = 'light' | 'medium' | 'heavy';
