export const AssetKeys = {
  map: 'map-background',
  shelter: 'shelter-states',
  huchu: 'huchu',
  deokbae: 'deokbae',
  poopMale: 'enemy-poop-male',
  poopFemale: 'enemy-poop-female',
  offLeashMale: 'enemy-offleash-male',
  offLeashFemale: 'enemy-offleash-female',
  trader: 'enemy-trader',
  breederMale: 'enemy-breeder-male',
  breederFemale: 'enemy-breeder-female',
  skillBark: 'skill-icon-bark',
  skillScold: 'skill-icon-scold',
  skillAquaBeam: 'skill-icon-aqua-beam',
  skillDeokbaeHowl: 'skill-icon-deokbae-howl',
  skillSafetyReport: 'skill-icon-safety-report',
} as const;
