export const AssetKeys = {
  white: '__WHITE',
  combatShapes: 'combat-shapes',
  enemyLabels: 'enemy-labels',
  damageNumberGlyphs: 'damage-number-glyphs',
  damageNumberLight: 'damage-number-light',
  damageNumberMedium: 'damage-number-medium',
  damageNumberHeavy: 'damage-number-heavy',
  map: 'map-background',
  huchuWalk: 'huchu-walk',
  huchuAttack: 'huchu-attack',
  huchuTailSwipe: 'huchu-tail-swipe',
  deokbaeWalk: 'deokbae-walk',
  deokbaeAttack: 'deokbae-attack',
  poopMaleWalk: 'poop-male-walk',
  poopMaleAttack: 'poop-male-attack',
  poopFemaleWalk: 'poop-female-walk',
  poopFemaleAttack: 'poop-female-attack',
  offLeashMaleWalk: 'offleash-male-walk',
  offLeashMaleAttack: 'offleash-male-attack',
  offLeashFemaleWalk: 'offleash-female-walk',
  offLeashFemaleAttack: 'offleash-female-attack',
  trader: 'enemy-trader',
  breederMaleWalk: 'breeder-male-walk',
  breederMaleAttack: 'breeder-male-attack',
  breederFemaleWalk: 'breeder-female-walk',
  breederFemaleAttack: 'breeder-female-attack',
} as const;
